extends: _base.yaml
name: generalizing_grasp_realsense
detector: generalizing_grasp
camera: realsense
paths:
  local_cloud_train: ${GRARE_DATA_ROOT}/relabeled/generalizing_grasp/realsense/local_cloud/train
  local_cloud_test: ${GRARE_DATA_ROOT}/relabeled/generalizing_grasp/realsense/local_cloud/test
  object_pooled_train: ${GRARE_DATA_ROOT}/relabeled/generalizing_grasp/realsense/object_pooled/train
  object_pooled_test: ${GRARE_DATA_ROOT}/relabeled/generalizing_grasp/realsense/object_pooled/test
  checkpoint_dir: ${GRARE_OUTPUT_ROOT}/checkpoints/generalizing_grasp_realsense
  rerank_dir: ${GRARE_OUTPUT_ROOT}/predictions/generalizing_grasp_realsense
  eval_dir: ${GRARE_OUTPUT_ROOT}/evaluation/generalizing_grasp_realsense
