extends: _base.yaml
name: rngnet_realsense
detector: rngnet
camera: realsense
paths:
  local_cloud_train: ${GRARE_DATA_ROOT}/relabeled/rngnet/realsense/local_cloud/train
  local_cloud_test: ${GRARE_DATA_ROOT}/relabeled/rngnet/realsense/local_cloud/test
  object_pooled_train: ${GRARE_DATA_ROOT}/relabeled/rngnet/realsense/object_pooled/train
  object_pooled_test: ${GRARE_DATA_ROOT}/relabeled/rngnet/realsense/object_pooled/test
  checkpoint_dir: ${GRARE_OUTPUT_ROOT}/checkpoints/rngnet_realsense
  rerank_dir: ${GRARE_OUTPUT_ROOT}/predictions/rngnet_realsense
  eval_dir: ${GRARE_OUTPUT_ROOT}/evaluation/rngnet_realsense
