#!/usr/bin/env bash
# Create and validate the local asset workspace used by GraRe.
#
# GraspNet-1Billion and frozen-detector candidate dumps are not redistributed
# by this repository. Obtain them from their original public sources, then use
# --check to verify that the workspace is ready for feature construction.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: ./scripts/prepare_data_assets.sh [options]

Create a local GraRe asset workspace and write <workspace>/grare_paths.env.
The optional public backbone download obtains MobileSAM and Point-MAE only.
GraspNet-1Billion and frozen-detector candidate dumps must be obtained from
their original public sources and are never downloaded or redistributed here.

Options:
  --workspace DIR           Asset workspace (default: ./grare-assets)
  --graspnet-root DIR       Existing GraspNet-1Billion root (default: <workspace>/graspnet)
  --detector-dumps DIR      Existing root containing frozen-detector .npy dumps
                            (default: <workspace>/detector_dumps)
  --download-backbones      Download public MobileSAM and Point-MAE weights
  --check                   Validate required assets and exit nonzero if any are missing
  --dry-run                 Print planned actions without writing or downloading
  -h, --help                Show this help text
EOF
}

workspace="$(pwd)/grare-assets"
graspnet_root=""
detector_dumps=""
download_backbones=false
check_only=false
dry_run=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --workspace)
      workspace="$2"
      shift 2
      ;;
    --graspnet-root)
      graspnet_root="$2"
      shift 2
      ;;
    --detector-dumps)
      detector_dumps="$2"
      shift 2
      ;;
    --download-backbones)
      download_backbones=true
      shift
      ;;
    --check)
      check_only=true
      shift
      ;;
    --dry-run)
      dry_run=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$graspnet_root" ]]; then
  graspnet_root="$workspace/graspnet"
fi
if [[ -z "$detector_dumps" ]]; then
  detector_dumps="$workspace/detector_dumps"
fi

backbone_dir="$workspace/backbones"
data_root="$workspace/grare_data"
output_root="$workspace/grare_output"
env_file="$workspace/grare_paths.env"

show_plan() {
  printf '%s\n' "Asset workspace: $workspace"
  printf '%s\n' "  GraspNet root: $graspnet_root"
  printf '%s\n' "  Detector dumps: $detector_dumps"
  printf '%s\n' "  Backbones: $backbone_dir"
  printf '%s\n' "  Prepared data: $data_root"
  printf '%s\n' "  Outputs: $output_root"
}

write_env_file() {
  printf '%s\n' '# Generated by scripts/prepare_data_assets.sh. Source this file from the repository root.' > "$env_file"
  printf 'export GRASPNET_ROOT=%q\n' "$graspnet_root" >> "$env_file"
  printf 'export GRARE_DUMP_ROOT=%q\n' "$detector_dumps" >> "$env_file"
  printf 'export GRARE_DATA_ROOT=%q\n' "$data_root" >> "$env_file"
  printf 'export GRARE_OUTPUT_ROOT=%q\n' "$output_root" >> "$env_file"
  printf 'export GRARE_SAM_CKPT=%q\n' "$backbone_dir/mobile_sam.pt" >> "$env_file"
  printf 'export GRARE_POINT_MAE_CKPT=%q\n' "$backbone_dir/point_mae_pretrain.pth" >> "$env_file"
}

validate_workspace() {
  local missing=0
  if [[ ! -d "$graspnet_root/scenes" ]]; then
    printf 'MISSING: GraspNet scenes directory: %s/scenes\n' "$graspnet_root" >&2
    missing=1
  fi
  if ! find "$detector_dumps" -type f -name '*.npy' -print -quit 2>/dev/null | grep -q .; then
    printf 'MISSING: frozen-detector .npy dumps under: %s\n' "$detector_dumps" >&2
    missing=1
  fi
  if [[ ! -s "$backbone_dir/mobile_sam.pt" ]]; then
    printf 'MISSING: MobileSAM checkpoint: %s/mobile_sam.pt\n' "$backbone_dir" >&2
    missing=1
  fi
  if [[ ! -s "$backbone_dir/point_mae_pretrain.pth" ]]; then
    printf 'MISSING: Point-MAE checkpoint: %s/point_mae_pretrain.pth\n' "$backbone_dir" >&2
    missing=1
  fi
  if [[ "$missing" -ne 0 ]]; then
    return 1
  fi
  printf 'Asset check passed. Source %s before running a paper configuration.\n' "$env_file"
}

show_plan
if [[ "$dry_run" == true ]]; then
  printf '%s\n' 'Dry run: no directories, environment file, or downloads were created.'
  exit 0
fi

mkdir -p "$workspace" "$graspnet_root" "$detector_dumps" "$backbone_dir" "$data_root" "$output_root"
write_env_file
printf 'Wrote environment file: %s\n' "$env_file"

if [[ "$download_backbones" == true ]]; then
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  "$script_dir/download_public_backbones.sh" "$backbone_dir"
fi

if [[ "$check_only" == true ]]; then
  validate_workspace
else
  printf '%s\n' 'Next: place GraspNet under the listed GraspNet root, add frozen-detector dumps, then run this script with --check.'
fi
