#!/usr/bin/env bash
# Create the local asset workspace used by GraRe and write its path environment.
#
# This script never downloads anything. GraspNet-1Billion, the frozen-detector
# checkpoints, and the MobileSAM and Point-MAE backbone weights must be obtained
# from their original official sources under their own licenses; see the README
# "Downloads" section for the official links and the target directory for each
# file. Use scripts/check_downloaded_assets.sh to verify placement afterwards.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: ./scripts/prepare_data_assets.sh [options]

Create a local GraRe asset workspace and write <workspace>/grare_paths.env.
No assets are downloaded: obtain GraspNet-1Billion, the detector checkpoints,
MobileSAM, and Point-MAE from their official sources (see the README Downloads
section) and place them in the directories printed by this script.

Options:
  --workspace DIR           Asset workspace (default: ./grare-assets)
  --graspnet-root DIR       Existing GraspNet-1Billion root (default: <workspace>/graspnet)
  --detector-dumps DIR      Root for frozen-detector .npy dumps
                            (default: <workspace>/detector_dumps)
  --dry-run                 Print planned layout without creating anything
  -h, --help                Show this help text

Verification:
  ./scripts/check_downloaded_assets.sh              downloaded assets (Stage 2)
  ./scripts/check_downloaded_assets.sh --with-dumps adds detector dumps (Stage 3)
EOF
}

workspace="$(pwd)/grare-assets"
graspnet_root=""
detector_dumps=""
dry_run=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --workspace)
      workspace="$2"
      shift 2
      ;;
    --graspnet-root)
      graspnet_root="$2"
      shift 2
      ;;
    --detector-dumps)
      detector_dumps="$2"
      shift 2
      ;;
    --dry-run)
      dry_run=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$graspnet_root" ]]; then
  graspnet_root="$workspace/graspnet"
fi
if [[ -z "$detector_dumps" ]]; then
  detector_dumps="$workspace/detector_dumps"
fi

backbone_dir="$workspace/backbones"
detector_checkpoint_root="$workspace/detector_checkpoints"
data_root="$workspace/grare_data"
output_root="$workspace/grare_output"
env_file="$workspace/grare_paths.env"

show_plan() {
  printf '%s\n' "Asset workspace: $workspace"
  printf '%s\n' "  GraspNet root: $graspnet_root"
  printf '%s\n' "  Detector dumps: $detector_dumps"
  printf '%s\n' "  Detector checkpoints: $detector_checkpoint_root"
  printf '%s\n' "  Backbones: $backbone_dir"
  printf '%s\n' "  Prepared data: $data_root"
  printf '%s\n' "  Outputs: $output_root"
}

write_env_file() {
  printf '%s\n' '# Generated by scripts/prepare_data_assets.sh. Source this file from the repository root.' > "$env_file"
  printf 'export GRASPNET_ROOT=%q\n' "$graspnet_root" >> "$env_file"
  printf 'export GRARE_DUMP_ROOT=%q\n' "$detector_dumps" >> "$env_file"
  printf 'export GRARE_DETECTOR_CKPT_ROOT=%q\n' "$detector_checkpoint_root" >> "$env_file"
  printf 'export GRARE_DATA_ROOT=%q\n' "$data_root" >> "$env_file"
  printf 'export GRARE_OUTPUT_ROOT=%q\n' "$output_root" >> "$env_file"
  printf 'export GRARE_SAM_CKPT=%q\n' "$backbone_dir/mobile_sam.pt" >> "$env_file"
  printf 'export GRARE_POINT_MAE_CKPT=%q\n' "$backbone_dir/point_mae_pretrain.pth" >> "$env_file"
  printf '%s\n' '# Prevent one thread pool per worker; explicit user settings take precedence.' >> "$env_file"
  printf '%s\n' 'export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"' >> "$env_file"
  printf '%s\n' 'export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"' >> "$env_file"
  printf '%s\n' 'export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"' >> "$env_file"
  printf '%s\n' 'export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-1}"' >> "$env_file"
}

show_plan
if [[ "$dry_run" == true ]]; then
  printf '%s\n' 'Dry run: no directories or environment file were created.'
  exit 0
fi

mkdir -p "$workspace" "$graspnet_root" "$detector_dumps" "$detector_checkpoint_root" "$backbone_dir" "$data_root" "$output_root"
write_env_file
printf 'Wrote environment file: %s\n' "$env_file"
printf '%s\n' 'Next: download the assets listed in the README Downloads section from their'
printf '%s\n' 'official sources into the directories above, then run:'
printf '%s\n' '  ./scripts/check_downloaded_assets.sh'
