#!/usr/bin/env bash
# Create and validate the local asset workspace used by GraRe.
#
# GraspNet-1Billion and frozen-detector candidate dumps are not redistributed
# by this repository. Obtain them from their original public sources, then use
# --check to verify that the workspace is ready for feature construction.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: ./scripts/prepare_data_assets.sh [options]

Create a local GraRe asset workspace and write <workspace>/grare_paths.env.
The optional public backbone download obtains MobileSAM and Point-MAE only.
GraspNet-1Billion, detector checkpoints, and frozen-detector candidate dumps
must be obtained from their original public sources and are never downloaded
or redistributed here.

Options:
  --workspace DIR           Asset workspace (default: ./grare-assets)
  --graspnet-root DIR       Existing GraspNet-1Billion root (default: <workspace>/graspnet)
  --detector-dumps DIR      Existing root containing frozen-detector .npy dumps
                            (default: <workspace>/detector_dumps)
  --detector-checkpoints DIR
                            Existing root containing one checkpoint directory per
                            paper setting (default: <workspace>/detector_checkpoints)
  --download-backbones      Download public MobileSAM and Point-MAE weights
  --setting NAME            Check one setting: gn_realsense, gn_kinect,
                            sbg_realsense, eg_realsense, or eg_kinect
  --all-paper-settings      Check candidate dumps for all five paper settings
  --require-detector-checkpoints
                            Also require detector-checkpoint files. Without
                            --setting, this checks all five settings.
  --check                   Validate required assets and exit nonzero if any are missing
  --dry-run                 Print planned actions without writing or downloading
  -h, --help                Show this help text
EOF
}

workspace="$(pwd)/grare-assets"
graspnet_root=""
detector_dumps=""
detector_checkpoints=""
download_backbones=false
check_only=false
setting=""
all_paper_settings=false
require_detector_checkpoints=false
dry_run=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --workspace)
      workspace="$2"
      shift 2
      ;;
    --graspnet-root)
      graspnet_root="$2"
      shift 2
      ;;
    --detector-dumps)
      detector_dumps="$2"
      shift 2
      ;;
    --detector-checkpoints)
      detector_checkpoints="$2"
      shift 2
      ;;
    --download-backbones)
      download_backbones=true
      shift
      ;;
    --check)
      check_only=true
      shift
      ;;
    --setting)
      setting="$2"
      shift 2
      ;;
    --all-paper-settings)
      all_paper_settings=true
      shift
      ;;
    --require-detector-checkpoints)
      require_detector_checkpoints=true
      shift
      ;;
    --dry-run)
      dry_run=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$graspnet_root" ]]; then
  graspnet_root="$workspace/graspnet"
fi
if [[ -z "$detector_dumps" ]]; then
  detector_dumps="$workspace/detector_dumps"
fi
if [[ -z "$detector_checkpoints" ]]; then
  detector_checkpoints="$workspace/detector_checkpoints"
fi
if [[ -n "$setting" && "$all_paper_settings" == true ]]; then
  printf '%s\n' 'Use either --setting or --all-paper-settings, not both.' >&2
  exit 2
fi
if [[ "$require_detector_checkpoints" == true && -z "$setting" && "$all_paper_settings" == false ]]; then
  all_paper_settings=true
fi

backbone_dir="$workspace/backbones"
data_root="$workspace/grare_data"
output_root="$workspace/grare_output"
env_file="$workspace/grare_paths.env"

show_plan() {
  printf '%s\n' "Asset workspace: $workspace"
  printf '%s\n' "  GraspNet root: $graspnet_root"
  printf '%s\n' "  Detector dumps: $detector_dumps"
  printf '%s\n' "  Detector checkpoints: $detector_checkpoints"
  printf '%s\n' "  Backbones: $backbone_dir"
  printf '%s\n' "  Prepared data: $data_root"
  printf '%s\n' "  Outputs: $output_root"
}

write_env_file() {
  printf '%s\n' '# Generated by scripts/prepare_data_assets.sh. Source this file from the repository root.' > "$env_file"
  printf 'export GRASPNET_ROOT=%q\n' "$graspnet_root" >> "$env_file"
  printf 'export GRARE_DUMP_ROOT=%q\n' "$detector_dumps" >> "$env_file"
  printf 'export GRARE_DETECTOR_CKPT_ROOT=%q\n' "$detector_checkpoints" >> "$env_file"
  printf 'export GRARE_DATA_ROOT=%q\n' "$data_root" >> "$env_file"
  printf 'export GRARE_OUTPUT_ROOT=%q\n' "$output_root" >> "$env_file"
  printf 'export GRARE_SAM_CKPT=%q\n' "$backbone_dir/mobile_sam.pt" >> "$env_file"
  printf 'export GRARE_POINT_MAE_CKPT=%q\n' "$backbone_dir/point_mae_pretrain.pth" >> "$env_file"
}

has_nonempty_file() {
  local root="$1"
  local pattern="$2"
  find "$root" -type f -name "$pattern" -size +0c -print -quit 2>/dev/null | grep -q .
}

setting_paths() {
  case "$1" in
    gn_realsense) printf '%s\n' 'graspnet_baseline realsense' ;;
    gn_kinect) printf '%s\n' 'graspnet_baseline kinect' ;;
    sbg_realsense) printf '%s\n' 'scale_balanced_grasp realsense' ;;
    eg_realsense) printf '%s\n' 'economicgrasp realsense' ;;
    eg_kinect) printf '%s\n' 'economicgrasp kinect' ;;
    *) return 1 ;;
  esac
}

validate_setting() {
  local name="$1"
  local detector camera
  if ! read -r detector camera < <(setting_paths "$name"); then
    printf 'Unknown paper setting: %s\n' "$name" >&2
    return 1
  fi
  local split
  for split in train test; do
    if ! has_nonempty_file "$detector_dumps/$detector/$camera/$split" '*.npy'; then
      printf 'MISSING: %s %s candidate dumps: %s/%s/%s/%s\n' \
        "$name" "$split" "$detector_dumps" "$detector" "$camera" "$split" >&2
      return 1
    fi
  done
  if [[ "$require_detector_checkpoints" == true ]] && ! has_nonempty_file "$detector_checkpoints/$name" '*'; then
    printf 'MISSING: %s detector checkpoint file under: %s/%s\n' \
      "$name" "$detector_checkpoints" "$name" >&2
    return 1
  fi
}

validate_workspace() {
  local missing=0
  if [[ ! -d "$graspnet_root/scenes" ]]; then
    printf 'MISSING: GraspNet scenes directory: %s/scenes\n' "$graspnet_root" >&2
    missing=1
  fi
  if [[ -n "$setting" ]]; then
    validate_setting "$setting" || missing=1
  elif [[ "$all_paper_settings" == true ]]; then
    local name
    for name in gn_realsense gn_kinect sbg_realsense eg_realsense eg_kinect; do
      validate_setting "$name" || missing=1
    done
  elif ! has_nonempty_file "$detector_dumps" '*.npy'; then
      printf 'MISSING: frozen-detector .npy dumps under: %s\n' "$detector_dumps" >&2
      missing=1
  fi
  if [[ ! -s "$backbone_dir/mobile_sam.pt" ]]; then
    printf 'MISSING: MobileSAM checkpoint: %s/mobile_sam.pt\n' "$backbone_dir" >&2
    missing=1
  fi
  if [[ ! -s "$backbone_dir/point_mae_pretrain.pth" ]]; then
    printf 'MISSING: Point-MAE checkpoint: %s/point_mae_pretrain.pth\n' "$backbone_dir" >&2
    missing=1
  fi
  if [[ "$missing" -ne 0 ]]; then
    return 1
  fi
  printf 'Asset check passed. Source %s before running a paper configuration.\n' "$env_file"
}

show_plan
if [[ "$dry_run" == true ]]; then
  printf '%s\n' 'Dry run: no directories, environment file, or downloads were created.'
  exit 0
fi

mkdir -p "$workspace" "$graspnet_root" "$detector_dumps" "$detector_checkpoints" "$backbone_dir" "$data_root" "$output_root"
write_env_file
printf 'Wrote environment file: %s\n' "$env_file"

if [[ "$download_backbones" == true ]]; then
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  "$script_dir/download_public_backbones.sh" "$backbone_dir"
fi

if [[ "$check_only" == true ]]; then
  validate_workspace
else
  printf '%s\n' 'Next: place GraspNet, detector checkpoints, and frozen-detector dumps in the listed roots, then run this script with --check.'
fi
